### ISSUE TITLE
Some question about FrozenOpenCLIPImageEmbedderV2

### ISSUE THREAD

**Issue by Kidleyh** [Drexubery/ViewCrafter#10]
Thank you very much for your work! My FrozenOpenCLIPImageEmbedderV2 reports an error saying there is no attribute 'input_patchnorm'. Since I manually downloaded the model open_clip_pytorch_model.bin in 'laion/CLIP-ViT-H-14-laion2B-s32B-b79K', I wonder if there is a problem here?
`AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'`
Or in the 'encode_with_vision_transformer' function in 'FrozenOpenCLIPImageEmbedderV2' (line 346 of the current file), is if or else generally used?

**Comment by Drexubery** [comment]
Hi, I uploaded the clip model weight [here](https://drive.google.com/file/d/1VwrBpR69IBVQ0qdfX4Syfg0DDsdHCH4u/view?usp=sharing). download it and modify the configs/inference_pvd_1024.yaml file by inputing its path: 
```
    cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        version: "<path to this file in your computer>"
        freeze: true
        layer: "penultimate"

    img_cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        version: "<path to this file in your computer>"
        freeze: true
```
Then it should work.
